version: "3"
services:
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myawesomedb